In [25]:
import numpy as np
import math
np.set_printoptions(suppress=True)

In [27]:
rotor_length = 500 - 15
rotor_depth = 45.5


rotor_volume =  13213.4 * math.pi*(1.75/2)**2 / 1000000000
#rotor_volume =  23679.529297 / 1000000000
rotor_cog = np.array([3.282484999999994, 0.7872119999999951, 243.970601])

rotor_density = 1250
rotor_mass = rotor_density * rotor_volume

rod_diameter = 2
rod_length = 500
rod_volume = rod_length * math.pi*(rod_diameter/2)**2 / 1000000000
# rod_density = 8500
rod_density = 19300
rod_cog = np.array([-6, 0.3, 0])
rod_mass = rod_density * rod_volume

rod2_diameter = 2
rod2_length = 500
rod2_volume = rod2_length * math.pi*(rod2_diameter/2)**2 / 1000000000
rod2_density = 8500
rod2_cog = np.array([3, 0.1, 0])
rod2_mass = rod2_density * rod2_volume

# rod3_diameter = 1
# rod3_length = 400
# rod3_volume = rod3_length * math.pi*(rod3_diameter/2)**2 / 1000000000
# rod3_density = 2270
# rod3_cog = np.array([rotor_depth/4 + 3.5, 0, rod3_length/2])
# rod3_mass = rod3_density * rod3_volume


print("Teziste rotoru bez vyztuhy", rotor_cog)
print("Hmotnost rotoru:", rotor_mass*1000, "g")
print("Teziste vyztuhy 1:", rod_cog)
print("Hmotnost vyztuhy 1:", rod_mass*1000, "g")
print("Teziste vyztuhy 2:", rod2_cog)
print("Hmotnost vyztuhy 2:", rod2_mass*1000, "g")

print("Celkova hmotnost: ", (rotor_mass + rod_mass + rod2_mass) *1000)

Teziste rotoru bez vyztuhy [  3.282485   0.787212 243.970601]
Hmotnost rotoru: 39.72743941559034 g
Teziste vyztuhy 1: [-6.   0.3  0. ]
Hmotnost vyztuhy 1: 30.3163691071415 g
Teziste vyztuhy 2: [3.  0.1 0. ]
Hmotnost vyztuhy 2: 13.35176877775662 g
Celkova hmotnost:  83.39557730048847


In [28]:
new_cog = ((rod3_mass * rod3_cog)+(rod2_mass * rod2_cog)+(rod_mass * rod_cog)+(rotor_mass * rotor_cog))/(rod_mass + rotor_mass + rod2_mass + rod3_mass)

print("Idealni X pozice: ", 0)
print("Celkove teziste:", new_cog)

Idealni X pozice:  0
Celkove teziste: [ -0.00987061   0.4958345  116.93146339]


In [18]:
import json
import math
import numpy as np
np.set_printoptions(suppress=True)

In [27]:
slicing = json.load(open('../CAD/amf/111_1009.json'))
print(slicing)

{'cog': {'X': 14.55228066396961, 'Y': -0.032508416639056965, 'Z': 192.1404119937146}, 'cog_stl': {'X': 14.55228066396961, 'Y': -0.032508416639056965, 'Z': 192.1404119937146}, 'file': '111_1009.gcode', 'material': {'density': 1.24, 'extrudate': 11278.032139999881, 'mass': 30.59374443895896, 'volume': 27126.84629657323}, 'slicer_translation': {'X': 0, 'Y': 0, 'Z': 0}}


In [28]:
x1 = np.array([slicing['cog']['X'], slicing['cog']['Y'], slicing['cog']['Z']])
m1 = slicing['material']['mass']

x2 = np.array([45.5/4 - 6.5, 0, slicing['cog']['Z']])
m2 = 400 * math.pi * (2.5/2)**2 * 8.73 / 1000

x3 = np.array([45.5/4 + 5, 0, slicing['cog']['Z']])
m3 = 400 * math.pi * (2/2)**2 * 1.5 / 1000

cog = (x1*m1) + (x2*m2) + (x3*m3)
cog /= (m1+m2+m3)

target = np.array([45.5/4, 0, 0])

print(x1, m1)
print(x2, m2)
print(x3, m3)

print(cog, m1+m2)

print(cog-target)

[ 14.55228066  -0.03250842 192.14041199] 30.59374443895896
[  4.875        0.         192.14041199] 17.14131491614931
[ 16.375        0.         192.14041199] 1.8849555921538759
[ 11.27848942  -0.02004341 192.14041199] 47.73505935510827
[ -0.09651058  -0.02004341 192.14041199]
